prod:
  image: vizzuality/rw-metadata:2.3.0${STAGING}
  ports:
    - "4000"
  env_file:
    - prod.env
  command: start
  dns: ${DNS_SERVER}
  restart: always
  log_driver: "syslog"
  log_opt:
    syslog-address: ${SYSLOG_ADDRESS}
    tag: rw-metadata${STAGING}
