develop:
  extends:
    file: base.yml
    service: base
  container_name: metadata-develop
  environment:
    CT_REGISTER_MODE: auto
    NODE_ENV: dev
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4000
    DEBUG: "*"
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/metadata/app
mongo:
  image: mongo:3.4
  container_name: metadata-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - $HOME/docker/data/metadata:/data/db
  restart: always
