develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35731:35729"
  container_name: rw-metadata-develop
  environment:
    CT_REGISTER_MODE: auto
    API_VERSION: v1
    CT_URL: http://mymachine:9000
    LOCAL_URL: http://mymachine:4000
    CT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
  command: develop
  links:
    - mongo
  volumes:
    - ./app:/opt/rw-metadata/app
mongo:
  image: mongo:3.4
  container_name: rw-metadata-mongo-develop
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - $HOME/docker/data/rw-metadata:/data/db
  restart: always
